blank_issues_enabled: true
contact_links:
  - name: Stel een vraag
    url: https://github.com/just-another-hackaton/reiziger-filament/discussions/categories/q-a
    about: Vraag de community om hulp.
  - name: Rapporteer een veiligheidslek
    url: https://github.com/just-another-hackaton/reiziger-filament/security/policy
    about: Ontdek hoe u ons op de hoogte kunt stellen van gevoelige bugs
