name: Update Changelog

on:
  release:
    types: [released]

permissions: {}

jobs:
  update:
    permissions:
      contents: write
    uses: sijot-turnhout/.github/.github/workflows/update-changelog.yml@main
